dataset: meta-mini-imagenet
train:
  split: meta-train
  image_size: 84
  normalization: True
  transform: flip
  n_batch: 200
  n_episode: 4
  n_way: 31
  n_shot: 1
  n_query: 15
val:
  split: meta-val
  image_size: 84
  normalization: True
  transform: flip
  n_batch: 200
  n_episode: 4
  n_way: 5
  n_shot: 1
  n_query: 15

encoder: resnet18
encoder_args:
  bn_args:
    track_running_stats: True
    episodic:
      - conv1
      - conv2
      - conv3
      - conv4
classifier: logistic

inner_args:
  reset_classifier: False
  n_step: 1
  encoder_lr: 0.01
  classifier_lr: 0.01
  momentum: 0.9
  weight_decay: 5.e-4
  first_order: False

optimizer: sgd
optimizer_args:
  lr: 0.01
  weight_decay: 5.e-4
  schedule: step
  milestones:
    - 10
    - 20
    - 50

epoch: 100